name: Coverage

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        php: [ '8.0' ]
        os: [ 'ubuntu' ]

    name: PHP ${{ matrix.php }} - ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: xdebug
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-style-php-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-style-php-${{ matrix.php }}-
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer update --prefer-dist --no-progress ${{ matrix.php >= 8.1 && '--ignore-platform-req=php' || '' }}

      - name: Run test suite
        run: vendor/bin/phpunit --verbose --coverage-text --coverage-clover=clover.xml
        env:
          COMPOSER_PROCESS_TIMEOUT: 0

      - name: Code Climate Test Reporter
        if: matrix.coverage
        uses: aktions/codeclimate-test-reporter@v1
        with:
          codeclimate-test-reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
          command: after-build -t clover
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        continue-on-error: true

      - name: Coverage
        run: bash <(curl -s https://codecov.io/bash)
