name: Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        php: [ '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3' ]
        os: [ 'windows', 'ubuntu' ]
        setup: [ 'lowest', 'stable' ]

    name: PHP ${{ matrix.php }} - ${{ matrix.setup }} - ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-v2-${{ matrix.php }}-${{ matrix.setup }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-php-v2-${{ matrix.php }}-${{ matrix.setup }}-
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: |
          ${{ matrix.php >= 8.2 && 'composer require --no-update nesbot/carbon:^2.62.1 --no-interaction --dev;' || '' }}
          composer update --prefer-dist --prefer-${{ matrix.setup }} --no-progress ${{ matrix.php >= 8.1 && '--ignore-platform-req=php' || '' }}

      - name: Run test suite
        run: vendor/bin/phpunit --verbose --no-coverage
        env:
          COMPOSER_PROCESS_TIMEOUT: 0
